openapi: 3.0.0
info:
  title: Hexlet Course API
  version: 0.0.0
tags: []
paths:
  /users:
    get:
      operationId: Users_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      operationId: Users_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFormData'
  /users/{id}:
    put:
      operationId: Users_update
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFormData'
    delete:
      operationId: Users_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
        - role
        - createdAt
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - admin
            - editor
            - viewer
        createdAt:
          type: string
          format: date-time
    UserFormData:
      type: object
      required:
        - name
        - email
        - role
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          minLength: 1
        role:
          type: string
          enum:
            - admin
            - editor
            - viewer
servers:
  - url: /api
    description: Development server
    variables: {}
